export const SET_FIELD = 'SET_FIELD';
export const SET_FILE = 'SET_FILE';
export const RESET_FORM = 'RESET_FORM';
export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';